import turtle
turtle.Screen().bgcolor("blueviolet")
sc=turtle.Screen()
sc.setup(500,500)
turtle.title("welcome to turtle website")
board=turtle.Turtle()
board.fillcolor("red")
board.begin_fill()
board.forward(100)
board.left(90)
board.forward(100)
board.left(90)
board.forward(100)
board.left(90)
board.forward(100)
board.left(90)

board.end_fill()

turtle.done()